config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :rooms do
    resources :bookings
  end

  resources :profiles, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accomodation.rb
class Accomodation

  attr_reader :key

  def initialize(key)
    @key = key.to_sym
  end

  def type
    TYPES[key]
  end

  def self.load(key)
    # We don't want to build TaxCodes with a nil key
    new(key) if key
  end

  def self.dump(accomodation)
    case accomodation
      when self then accomodation.key
      else accomodation
    end
  end

  def self.all
    TYPES.keys.map{|key| new(key)}
  end

  TYPES = {
    room: 'Room',
    flat: 'Flat',
    house: 'House'
  }

  def ==(other)
    if other.is_a?(self.class)
      key == other.key
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_destroy_commit { broadcast_remove_to "bookings" }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings
  belongs_to :user

  serialize :accomodation_type, Accomodation

  validates :name, :beds, presence: true

  validates :accomodation_type, inclusion: { in: Accomodation.all }

  # broadcasts
  # after_create_commit { broadcast_prepend_to('rooms', locals: { current_user: user, room: self }) }
  # after_update_commit { broadcast_replace_to('rooms', locals: { current_user: user, room: self }) }
  after_destroy_commit { broadcast_remove_to "rooms" }

  def accomodation
    accomodation_type.type if accomodation_type
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :bookings
  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  before_action :authenticate_user!

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]

  def create
    @booking = Booking.new(params_booking)
    @booking.room_id = params[:room_id]
    @booking.user = current_user
    authorize @booking
    respond_to do |format|
      if @booking.save
        format.html { redirect_to profile_path(current_user), notice: "Your booking was saved" }
      end
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    respond_to do |format| 
      if @booking.update(params_booking)
        format.html { redirect_to profile_path(current_user)}
      end
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def params_booking
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :skip_authorization

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room, only: [:show, :destroy, :edit, :update]
  
  def index
    @rooms = policy_scope(Room).order(created_at: :desc)
  end

  def show
    authorize @room
    @booking = Booking.new
  end
  
  def new
    @room = Room.new
    authorize @room
  end

  def edit
    authorize @room
  end

  def create
    @room = Room.new(params_room)
    @room.user = current_user
    authorize @room
    binding.pry

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path }
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('rooms', @room, locals: { current_user: current_user, room: @room }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@room, partial: 'rooms/form', locals: { room: @room }) }
      end
    end
  end


  def update
    authorize @room
    respond_to do |format|
      if @room.update(params_room)
        format.turbo_stream { render turbo_stream: turbo_stream.update(@room, partial: 'rooms/room', locals: { room: @room })}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@room, partial: 'rooms/form', locals: { room: @room }) }
      end
    end
  end

  def destroy
    authorize @room
    @room.destroy
  end

  private

  def params_room
    params.require(:room).permit(:beds, :name, :accomodation_type)
  end

  def find_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_booking.html.erb
<div class="card-booking">
  <%= turbo_frame_tag dom_id(booking) do %>
    <p>Réservation <%= booking.room.name %></p>
    <p>Du : <%= booking.start_date.strftime("%d%m%y") %></p>
    <p>Au : <%= booking.end_date.strftime("%d%m%y") %></p>
    <div class="d-flex">
      <%= link_to "Edit", edit_room_booking_path(booking.room, booking), class: 'btn btn-warning'  %>
      <%= button_to "Destroy", room_booking_path(booking.room, booking), method: :delete, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<%= turbo_frame_tag dom_id(@booking) do %>
  <%= simple_form_for [@booking.room, @booking] do |f| %>
    <%= f.input :start_date, as: :date %>
    <%= f.input :end_date, as: :date %>
    <%= f.submit "Validate", class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Accéder à l'application test d'Hotwire</h1>
<%= link_to "See rooms", rooms_path %>

<p>L'application est une plateforme type Airbnb ou l'utilisateur peut ajouter des chambres ou reserver une chambre</p>

app/views/profiles/show.html.erb
<h1>My profile</h1>
<%= @user.email %>

<%= turbo_stream_from 'bookings' %>
<%= turbo_frame_tag 'bookings' do %>
  <% @user.bookings.each do |booking| %>
    <%= render 'bookings/booking', booking: booking %>
  <% end %>
<% end %>

app/views/rooms/_form.html.erb
<%= turbo_frame_tag @room do %>
  <%= simple_form_for @room, id: dom_id(@room), data: { controller: 'form', action: 'turbo:submit-end->form#reset' } do |f| %>
    <%= f.input :name %>
    <%= f.input :beds %>
    <%= f.input :accomodation_type, collection: Accomodation::TYPES.map {|key, value| [value, key] }, selected: Accomodation::TYPES.assoc(@room.accomodation_type.key) || Accomodation::TYPES.first %>
    <%= f.submit "Validate", class: 'btn btn-primary' %>
  <% end %>
  <%= link_to "Back", rooms_path, class: 'btn btn-secondary' %>
<% end %>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag dom_id(room) do %>
  <div class="card-room">
    <p>Name : <%= room.name %></p>
    <p>Type of accomodation : <%= room.accomodation %></p>
    <p>Number of beds : <%= room.beds %></p>
    <% if params[:action] != 'show' %>
      <%= link_to "Show", room_path(room), target: "_top", class: 'btn btn-primary' %>
      <% if room.user == current_user %>
        <%= link_to "Edit", edit_room_path(room), class: 'btn btn-warning' %>
      <% end %>
      <% if room.user == current_user %>
        <%= button_to "Delete", room, method: :delete, class: 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<%= turbo_frame_tag "new_room" do %>
  <%= link_to 'Create a new room', new_room_path, class: 'btn btn-primary' %>
<% end %>
<%= turbo_stream_from "rooms" %>
<%= turbo_frame_tag "rooms" do %>
  <%= render @rooms %>
<% end %>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<%= render @room %>

<%= simple_form_for [@room, @booking] do |f| %>
  <%= f.input :start_date, as: :date %>
  <%= f.input :end_date, as: :date %>
  <%= f.submit "Book", class: 'btn btn-primary' %>
<% end %>

<%= link_to "Back", rooms_path, class: 'btn btn-secondary' %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="d-flex">
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-success' %>
    <%= link_to "Mes résas", profile_path(current_user), class: 'btn btn-secondary' %>
    <%= link_to "Voir les rooms", rooms_path, class: 'btn btn-secondary' %>
  </div>
<% else %>
  <%= link_to "Sign in", new_user_session_path, method: :delete, class: 'btn btn-success' %>
<% end %>